#ifndef ARCH_INCLUDE_ASM_IIA_H
#define ARCH_INCLUDE_ASM_IIA_H

#ifndef __ASSEMBLY__
#include <asm/io.h>
#include <linux/spinlock.h>

#define INT_NUM(group, idx)    (((group)<<5)+(idx))
#define GET_INT_GROUP(irq)        ((irq)>>5)
#define GET_INT_NUM(irq)          ((irq)&31)

#define IIA_AVS_INT         	INT_NUM(0, 0)
#define IIA_ASRC_INT      		INT_NUM(0, 1)
#define IIA_DISP0_INT      		INT_NUM(0,2)
#define IIA_DISP1_INT      		INT_NUM(0,3)
#define IIA_ETHR0_INT      		INT_NUM(0, 4)
#define IIA_ETHR1_INT     		INT_NUM(0, 5)
#define IIA_FES0_INT     		INT_NUM(0, 6)
#define IIA_FES1_INT     		INT_NUM(0, 7)
#define IIA_G2D_INT     		INT_NUM(0, 8)
#define IIA_G3D_INT         	INT_NUM(0, 9)
#define IIA_GIC_INT         	INT_NUM(0, 10)
#define IIA_I2S_TX_INT      	INT_NUM(0, 11)
#define IIA_IRC_INT         	INT_NUM(0, 12)
#define IIA_MAD_INT         	INT_NUM(0, 13)
#define IIA_MAFE_INT 		  	INT_NUM(0, 14)
#define IIA_MMAC_INT        	INT_NUM(0, 15)
#define IIA_NFC_INT         	INT_NUM(0, 16)
#define IIA_NRFC_INT     		INT_NUM(0, 17)
#define IIA_NSK_INT         	INT_NUM(0, 18)
#define IIA_PPC_INT         	INT_NUM(0, 19)
#define IIA_RBM_INT         	INT_NUM(0, 20)
#define IIA_SATA_INT        	INT_NUM(0, 21)
#define IIA_SMCC_INT        	INT_NUM(0, 22)
#define IIA_SPDIF_TX_INT    	INT_NUM(0, 23)
#define IIA_UART0_INT       	INT_NUM(0, 24)
#define IIA_UART1_INT       	INT_NUM(0, 25)
#define IIA_UART2_INT       	INT_NUM(0, 26)
#define IIA_UART3_INT       	INT_NUM(0, 27)
#define IIA_USBH3_INT       	INT_NUM(0, 28)
#define IIA_USBH_INT 		   	INT_NUM(0, 29)
#define IIA_VHE1_INT    		INT_NUM(0, 30)
#define IIA_VNE_INT    			INT_NUM(0, 31)

#define IIA_NIS_INT				INT_NUM(1,   0)
#define IIA_PROC0_IPC0_INT		INT_NUM(1,   1)
#define IIA_PROC0_IPC1_INT		INT_NUM(1,   2)
#define IIA_PROC1_IPC0_INT		INT_NUM(1,   3)
#define IIA_PROC1_IPC1_INT		INT_NUM(1,   4)
#define IIA_PROC2_IPC0_INT		INT_NUM(1,   5)
#define IIA_PROC2_IPC1_INT		INT_NUM(1,   6)
#define IIA_PROC4_IPC0_INT		INT_NUM(1,   7)
#define IIA_PROC4_IPC1_INT		INT_NUM(1,   8)
#define IIA_PROC5_IPC0_INT		INT_NUM(1,   9)
#define IIA_PROC5_IPC1_INT 		INT_NUM(1,  10)
#define IIA_PROC6_IPC0_INT 		INT_NUM(1,  11)
#define IIA_PROC6_IPC1_INT 		INT_NUM(1,  12)
#define IIA_PROC8_IPC0_INT 		INT_NUM(1,  13)
#define IIA_PROC8_IPC1_INT 		INT_NUM(1,  14)
#define IIA_PROC9_IPC0_INT 		INT_NUM(1,  15)
#define IIA_PROC9_IPC1_INT 		INT_NUM(1,  16)
#define IIA_PROC10_IPC0_INT 	INT_NUM(1,  17)
#define IIA_PROC10_IPC1_INT 	INT_NUM(1,  18)
#define IIA_PROC11_IPC0_INT 	INT_NUM(1,  19)
#define IIA_PROC11_IPC1_INT 	INT_NUM(1,  20)
#define IIA_PROC12_IPC0_INT 	INT_NUM(1,  21)
#define IIA_PROC12_IPC1_INT 	INT_NUM(1,  22)
#define IIA_PROC13_IPC0_INT 	INT_NUM(1,  23)
#define IIA_PROC13_IPC1_INT 	INT_NUM(1,  24)
#define IIA_PROC14_IPC0_INT 	INT_NUM(1,  25)
#define IIA_PROC14_IPC1_INT 	INT_NUM(1,  26)
#define IIA_HOST_IPC0_INT 		INT_NUM(1,  27)
#define IIA_HOST_IPC1_INT 		INT_NUM(1,  28)
#define IIA_RMX0_INT			INT_NUM(1, 	29)
#define IIA_RMX1_INT			INT_NUM(1, 	30)
#define IIA_RSA_INT				INT_NUM(1, 	31)

#define IIA_TSD_DAT0_INT  		INT_NUM(2,   0)
#define IIA_TSD_DAT1_INT  		INT_NUM(2,   1)
#define IIA_TSD_DAT2_INT  		INT_NUM(2,   2)
#define IIA_TSD_DAT3_INT  		INT_NUM(2,   3)
#define IIA_TSD_DAT4_INT  		INT_NUM(2,   4)
#define IIA_TSD_DAT5_INT  		INT_NUM(2,   5)
#define IIA_TSD_DAT6_INT  		INT_NUM(2,   6)
#define IIA_TSD_DAT7_INT  		INT_NUM(2,   7)
#define IIA_TSD_DAT8_INT  		INT_NUM(2,   8)
#define IIA_TSD_DAT9_INT  		INT_NUM(2,   9)
#define IIA_TSD_DAT10_INT  		INT_NUM(2,  10)
#define IIA_TSD_DAT11_INT  		INT_NUM(2,  11)
#define IIA_TSD_DAT12_INT  		INT_NUM(2,  12)
#define IIA_TSD_DAT13_INT  		INT_NUM(2,  13)
#define IIA_TSD_DAT14_INT  		INT_NUM(2,  14)
#define IIA_TSD_DAT15_INT  		INT_NUM(2,  15)
#define IIA_TSD_DAT16_INT  		INT_NUM(2,  16)
#define IIA_TSD_DAT17_INT  		INT_NUM(2,  17)
#define IIA_TSD_DAT18_INT  		INT_NUM(2,  18)
#define IIA_TSD_DAT19_INT  		INT_NUM(2,  19)
#define IIA_TSD_DAT20_INT  		INT_NUM(2,  20)
#define IIA_TSD_DAT21_INT  		INT_NUM(2,  21)
#define IIA_TSD_DAT22_INT  		INT_NUM(2,  22)
#define IIA_TSD_DAT23_INT  		INT_NUM(2,  23)
#define IIA_TSD_DAT24_INT  		INT_NUM(2,  24)
#define IIA_TSD_DAT25_INT  		INT_NUM(2,  25)
#define IIA_TSD_DAT26_INT  		INT_NUM(2,  26)
#define IIA_TSD_DAT27_INT  		INT_NUM(2,  27)
#define IIA_TSD_DAT28_INT  		INT_NUM(2,  28)
#define IIA_TSD_DAT29_INT  		INT_NUM(2,  29)
#define IIA_TSD_DAT30_INT  		INT_NUM(2,  30)
#define IIA_TSD_DAT31_INT  		INT_NUM(2,  31)

#define IIA_DMA1_A0_INT			INT_NUM(3,   0)
#define IIA_DMA1_A1_INT			INT_NUM(3,   1)
#define IIA_DMA1_B0_INT			INT_NUM(3,   2)
#define IIA_DMA1_B1_INT	    	INT_NUM(3,   3)
#define IIA_DMA_A0_INT		    INT_NUM(3,   4)
#define IIA_DMA_A1_INT		    INT_NUM(3,   5)
#define IIA_DMA_B0_INT		    INT_NUM(3,   6)
#define IIA_DMA_B1_INT			INT_NUM(3,   7)
#define IIA_EDC_INT		    	INT_NUM(3,   8)
#define IIA_EE_INT				INT_NUM(3,   9)
#define IIA_FESB0_INT 			INT_NUM(3,  10)
#define IIA_FESB1_INT 			INT_NUM(3,  11)
#define IIA_FFD_INT 			INT_NUM(3,  12)
#define IIA_GVD_INT 			INT_NUM(3,  13)
#define IIA_I2S_INT 			INT_NUM(3,  14)
#define IIA_MOCA_INT 			INT_NUM(3,  15)
#define IIA_MOCA_CB23_INT 		INT_NUM(3,  16)
#define IIA_MPP_INT 			INT_NUM(3,  17)
#define IIA_MPPE_INT 			INT_NUM(3,  18)
#define IIA_SPDIF_RX_INT 		INT_NUM(3,  19)
#define IIA_TME1_INT 			INT_NUM(3,  20)
#define IIA_TME_INT 			INT_NUM(3,  21)
#define IIA_TSD_ERR_INT 		INT_NUM(3,  22)
#define IIA_TSD_MISC_INT 		INT_NUM(3,  23)
#define IIA_VHE_INT 			INT_NUM(3,  24)
#define IIA_AON_INT 			INT_NUM(3,  25)
#define IIA_P4_ECL_INT			INT_NUM(3,  26)
#define IIA_P4_MBOX_INT			INT_NUM(3,  27)
#define IIA_P4_NTA_INT			INT_NUM(3,  28)
#define IIA_P6_MBOX_INT			INT_NUM(3,  29)
#define IIA_P0_INT				INT_NUM(3,  30)
#define IIA_P1_INT				INT_NUM(3,  31)

#define IIA_P2_INT				INT_NUM(4,   0)
#define IIA_P4_INT				INT_NUM(4,   1)
#define IIA_P5_INT				INT_NUM(4,   2)
#define IIA_P6_INT				INT_NUM(4,   3)
#define IIA_P8_INT				INT_NUM(4,   4)
#define IIA_P9_INT				INT_NUM(4,   5)
#define IIA_P10_INT				INT_NUM(4,   6)
#define IIA_P11_INT				INT_NUM(4,   7)
#define IIA_P12_INT				INT_NUM(4,   8)
#define IIA_P13_INT				INT_NUM(4,   9)
#define IIA_P14_INT				INT_NUM(4,  10)

#define IIA_INT_END				INT_NUM(4,  11)

unsigned int IIAGenericWrite(unsigned int id, unsigned int type, unsigned int irq, unsigned int val);
unsigned int IIAGenericRead(unsigned int id, unsigned int type, unsigned int irq);

#define IIAHostWrite(type, irq, val)       				IIAGenericWrite(0, type, irq, val)
#define IIAHostRead(type, irq)             				IIAGenericRead(0, type, irq)
#define IIADbgWrite(type, irq, val)        				IIAGenericWrite(1, type, irq, val)
#define IIADbgRead(type, irq)              				IIAGenericRead(1, type, irq)
#define IIAProcWrite(proc, type, irq, val) 				IIAGenericWrite((proc)+2, type, irq, val)
#define IIAProcRead(proc, type, irq)       				IIAGenericRead((proc)+2, type, irq)


#define IIAProcWriteStatus(proc, irq, val)        		IIAProcWrite(proc, 0, irq, val)
#define IIAProcReadStatus(proc, irq)               		IIAProcRead(proc, 0, irq)
#define IIAProcWriteMask(proc, irq, val)           		IIAProcWrite(proc, 1, irq, val)
#define IIAProcReadMask(proc, irq)                 		IIAProcRead(proc, 1, irq)

#define LOCAL_PROC  5 //ARM proc

#define IIALocalWriteStatus(irq, val)       			IIAProcWrite(LOCAL_PROC, 0, irq, val)
#define IIALocalReadStatus(irq)             			IIAProcRead(LOCAL_PROC, 0, irq)
#define IIALocalWriteMask(irq, val)         			IIAProcWrite(LOCAL_PROC, 1, irq, val)
#define IIALocalReadMask(irq)               			IIAProcRead(LOCAL_PROC, 1, irq)

#define IIALocalClearInt(irq)       IIALocalWriteStatus(irq, 1<<GET_INT_NUM(irq))
#define IIALocalReadInt(irq)        (IIALocalReadStatus(irq)&(1<<GET_INT_NUM(irq)))
#define IIALocalSetMask(irq)        IIALocalWriteMask(irq, IIALocalReadMask(irq) | (1<<GET_INT_NUM(irq)))
#define IIALocalClearMask(irq)      IIALocalWriteMask(irq, IIALocalReadMask(irq) & ~(1<<GET_INT_NUM(irq)))

#define IIADumpStatus()            \
({ \
    int i; \
    for(i=0;i<=GET_INT_GROUP(IIA_INT_END);i++) \
        printk("IIA Grp %d: Status %08x Mask %08x\n", i, IIALocalReadStatus(i*32), IIALocalReadMask(i*32)); \
})                
#endif
#endif //ARCH_INCLUDE_ASM_IIA_H
