#ifndef INCLUDE_MACH_TIMEX_H
#define INCLUDE_MACH_TIMEX_H

#include <plat/timex.h>

#define GLOBAL_TIMER_COUNTER_LOWER_OFFSET 	0x0
#define GLOBAL_TIMER_COUNTER_UPPER_OFFSET	0x4
#define GLOBAL_TIMER_CONTROL_OFFSET			0x8
#define GLOBAL_TIMER_TIMER_EN			1
#define GLOBAL_TIMER_COMP_EN			2
#define GLOBAL_TIMER_IRQ_EN				4
#define GLOBAL_TIMER_AUTO_INC_EN		8
#define GLOBAL_TIMER_PRESCALE_MASK		0x0000ff00
#define GLOBAL_TIMER_INT_STATUS_OFFSET		0xc
#define GLOBAL_TIMER_COMP_LOWER_OFFSET		0x10
#define GLOBAL_TIMER_COMP_UPPER_OFFSET		0x14
#define GLOBAL_TIMER_AUTO_INC_OFFSET		0x18

#define PRIVATE_TIMER_LOAD_OFFSET 		0x00
#define PRIVATE_TIMER_COUNTER_OFFSET 	0x04
#define PRIVATE_TIMER_CONTROL_OFFSET 	0x08
#define PRIVATE_TIMER_TIMER_EN			1
#define PRIVATE_TIMER_AUTO_RELOAD		2
#define PRIVATE_TIMER_IRQ_EN			4
#define PRIVATE_TIMER_PRESCALE_MASK		0x0000ff00
#define PRIVATE_TIMER_INT_STATUS_OFFSET 0x0c

#define WATCHDOG_LOAD_OFFSET 			0x20
#define WATCHDOG_COUNTER_OFFSET 		0x24
#define WATCHDOG_CONTROL_OFFSET 		0x28
#define WATCHDOG_EN			1
#define WATCHDOG_MODE		8
#define WATCHDOG_INT_STATUS_OFFSET 		0x2c
#define WATCHDOG_RESET_OFFSET 			0x30
#define WATCHDOG_DISABLE_OFFSET 		0x34

#define PRIVATE_TIMER_REG(offset)   *(volatile unsigned int *)(CORE_PERIPHERAL_BASE+CORE_PRIVATE_TIMER_OFFSET+(offset))
#define GLOBAL_TIMER_REG(offset)   *(volatile unsigned int *)(CORE_PERIPHERAL_BASE+CORE_GLOBAL_TIMER_OFFSET+(offset))

#endif
